version: '3'
services:
  laravel:
    image: 'composer:2'
    working_dir: /var/www/html
    volumes:
      - ./my-laravel-app:/var/www/html
    ports:
      - '8000:8000'
    command: 'php artisan serve --host=0.0.0.0 --port=8000'

  nextjs:
    image: 'node:20'
    working_dir: /usr/src/app
    volumes:
      - ./my-nextjs-app:/usr/src/app
    ports:
      - '3000:3000'
    command: 'npm run dev'

#    test